pool:
  vmImage: 'ubuntu-16.04'
trigger:
  - master
steps:
- task: PowerShell@2

  displayName: create build pipeline

  inputs:

    targetType: 'inline'

    script:

     az pipelines create --name BuildPipeline --org https://dev.azure.com/vikramathreya2905/ --project NoSpace --repository NoSpace --branch master --skip-first-run true --service-connection vikramathreya2905-NoSpace-5ec7c132-93b8-485b-a746-baeea274ed96

