pool:
  vmImage: 'windows-latest'
trigger:
  - master
steps:
- task: PowerShell@2

  displayName: create build pipeline

  inputs:

    targetType: 'inline'

    script:

     az pipelines create --name 'ContosoBuild' --description 'Pipeline for contoso project' --repository https://github.com/Vikram2951997/ContosoAir.git --branch master

