pool:
  vmImage: 'ubuntu-16.04'

variables:
 - name: projectName
   value: contoso
trigger:
  - master
steps: 
- bash: echo $(projectName)
- powershell: echo $(projectName)
- script: echo $(projectName)
