pool:
  vmImage: 'windows-latest'
trigger:
  - master
steps:
- task: PowerShell@2

  displayName: create build pipeline

  inputs:

    targetType: 'inline'

    script:

     az login -u vikramathreya2905@outlook.com -p ThisisIt@291997~1
     az pipelines create --name TestPipe --org https://dev.azure.com/vikramathreya2905/ --project NoSapce --repository https://github.com/Vikram2951997/ContosoAir.git --branch master --yaml-path azure-pipelines.yml --skip-first-run true --service-connection vikramathreya2905-Git Local-5ec7c132-93b8-485b-a746-baeea274ed96




